import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'




export const metadata: Metadata = {
  title: 'ASBAPPCPW',
  description: 'Generated by Szafa',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Modal />
        </body>
    </html>
  )
}
